### PR TITLE
PI-996 move Guzzle to require-dev in composer.json

### PR DESCRIPTION
**Pull request by thellimist**
I did not change the guzzle version to 5.x. That is a big change regardless. Currently Guzzle 3.x works as expected. If we have any issues with it we can upgrade it.

### CODE REVIEW

**Comment by jwineman** [comment]
We can revert to the APIClient that was being used with 5.x right?

**Comment by jwineman** [comment]
@thellimist

**Comment by thellimist** [comment]
> We can revert to the APIClient that was being used with 5.x right?

Yes. There are multiple PR's with multiple commits. The order is important. I think we should test it after doing the reverts. Wanted to avoid deep testing the plugin.

**Comment by jwineman** [comment]
+1 to thoroughly test the 5.x reversion.

**Pull request merged**
