### PR TITLE
few changes

### PR DESCRIPTION
**Pull request by cheprasov**

### CODE REVIEW

**Comment by jwineman** [comment]
Hi,

Thanks for the PR!  Is there anything else going on here besides PSR code style changes?  Are you using the cloudflare-pluign-backend for anything?

Thanks,
John

**Comment by cheprasov** [comment]
Hello John. 
No, I do not use cloudflare-pluign-backend. Just I saw a opened vacancy of PHP developer in CloudFlare, and I viewed public php project on github to understand what kind of work you doing by PHP. And, at the same time, I decided to change some line.

**Comment by jwineman** [comment]
Hey,

We don't except outside changes on this repository but that being said I appreciate the initiative and agree with the changes you made.  We have PSR-2 formatting in our backlog.

I see you already applied to one of our PHP positions, I made a note about your PR.  

Thanks!
John

**Comment by cheprasov** [comment]
Hi John,
Thanks :)

**Pull request closed without merging**
